### ISSUE TITLE
Generate TFRecord

### ISSUE THREAD

**Issue by kamtafw** [nicknochnack/GenerateTFRecord#3]
Hi Nick, I have a pre-existing csv file containing img_name, xmin, ymin, xmax and ymax from an already labeled data I downloaded. I'm trying to come up with a tfrecord for my training but I'm kinda lost and confused. Do you know any way around this?

**Comment by longqua69** [comment]
Hi @tiva-0007 ,

Could you please help explain more details about your error? I have an issue while trying to execute this script by following the [TensorFlow Object Detection](https://www.youtube.com/watch?v=yqkISICHH-U&t=996s)
Below is the issue:
```
Traceback (most recent call last):
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1702, in _ParseAbstractInteger
    return int(text, 0)
ValueError: invalid literal for int() with base 0: "'1'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1652, in _ConsumeInteger
    result = ParseInteger(tokenizer.token, is_signed=is_signed, is_long=is_long)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1674, in ParseInteger
    result = _ParseAbstractInteger(text)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1704, in _ParseAbstractInteger
    raise ValueError('Couldn\'t parse integer: %s' % orig_text)
ValueError: Couldn't parse integer: '1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\utils\label_map_util.py", line 171, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 719, in Merge
    return MergeLines(
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 793, in MergeLines
    return parser.MergeLines(lines, message)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 818, in MergeLines
    self._ParseOrMerge(lines, message)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 837, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField
    merger(tokenizer, message, field)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1042, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField
    merger(tokenizer, message, field)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1076, in _MergeScalarField
    value = _ConsumeInt32(tokenizer)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1573, in _ConsumeInt32
    return _ConsumeInteger(tokenizer, is_signed=True, is_long=False)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1654, in _ConsumeInteger
    raise tokenizer.ParseError(str(e))
google.protobuf.text_format.ParseError: 3:6 : '	id: '1'
': Couldn't parse integer: '1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Open-Source_Contribution\object_dectection_tf\Tensorflow\scripts\generate_tfrecord.py", line 61, in <module>
    label_map = label_map_util.load_labelmap(args.labels_path)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\utils\label_map_util.py", line 173, in load_labelmap
    label_map.ParseFromString(label_map_string)
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1702, in _ParseAbstractInteger
    return int(text, 0)
ValueError: invalid literal for int() with base 0: "'1'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1652, in _ConsumeInteger
    result = ParseInteger(tokenizer.token, is_signed=is_signed, is_long=is_long)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1674, in ParseInteger
    result = _ParseAbstractInteger(text)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1704, in _ParseAbstractInteger
    raise ValueError('Couldn\'t parse integer: %s' % orig_text)
ValueError: Couldn't parse integer: '1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\utils\label_map_util.py", line 171, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 719, in Merge
    return MergeLines(
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 793, in MergeLines
    return parser.MergeLines(lines, message)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 818, in MergeLines
    self._ParseOrMerge(lines, message)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 837, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField
    merger(tokenizer, message, field)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1042, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField
    merger(tokenizer, message, field)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1076, in _MergeScalarField
    value = _ConsumeInt32(tokenizer)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1573, in _ConsumeInt32
    return _ConsumeInteger(tokenizer, is_signed=True, is_long=False)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1654, in _ConsumeInteger
    raise tokenizer.ParseError(str(e))
google.protobuf.text_format.ParseError: 3:6 : '	id: '1'
': Couldn't parse integer: '1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Open-Source_Contribution\object_dectection_tf\Tensorflow\scripts\generate_tfrecord.py", line 61, in <module>
    label_map = label_map_util.load_labelmap(args.labels_path)
  File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\utils\label_map_util.py", line 173, in load_labelmap
    label_map.ParseFromString(label_map_string)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by indrawun** [comment]
> Hi @tiva-0007 ,
> 
> Could you please help explain more details about your error? I have an issue while trying to execute this script by following the [TensorFlow Object Detection](https://www.youtube.com/watch?v=yqkISICHH-U&t=996s) Below is the issue:
> 
> ```
> Traceback (most recent call last):
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1702, in _ParseAbstractInteger
>     return int(text, 0)
> ValueError: invalid literal for int() with base 0: "'1'"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1652, in _ConsumeInteger
>     result = ParseInteger(tokenizer.token, is_signed=is_signed, is_long=is_long)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1674, in ParseInteger
>     result = _ParseAbstractInteger(text)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1704, in _ParseAbstractInteger
>     raise ValueError('Couldn\'t parse integer: %s' % orig_text)
> ValueError: Couldn't parse integer: '1'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\utils\label_map_util.py", line 171, in load_labelmap
>     text_format.Merge(label_map_string, label_map)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 719, in Merge
>     return MergeLines(
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 793, in MergeLines
>     return parser.MergeLines(lines, message)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 818, in MergeLines
>     self._ParseOrMerge(lines, message)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 837, in _ParseOrMerge
>     self._MergeField(tokenizer, message)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField
>     merger(tokenizer, message, field)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1042, in _MergeMessageField
>     self._MergeField(tokenizer, sub_message)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField
>     merger(tokenizer, message, field)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1076, in _MergeScalarField
>     value = _ConsumeInt32(tokenizer)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1573, in _ConsumeInt32
>     return _ConsumeInteger(tokenizer, is_signed=True, is_long=False)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1654, in _ConsumeInteger
>     raise tokenizer.ParseError(str(e))
> google.protobuf.text_format.ParseError: 3:6 : '	id: '1'
> ': Couldn't parse integer: '1'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "d:\Open-Source_Contribution\object_dectection_tf\Tensorflow\scripts\generate_tfrecord.py", line 61, in <module>
>     label_map = label_map_util.load_labelmap(args.labels_path)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\utils\label_map_util.py", line 173, in load_labelmap
>     label_map.ParseFromString(label_map_string)
> TypeError: a bytes-like object is required, not 'str'
> Traceback (most recent call last):
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1702, in _ParseAbstractInteger
>     return int(text, 0)
> ValueError: invalid literal for int() with base 0: "'1'"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1652, in _ConsumeInteger
>     result = ParseInteger(tokenizer.token, is_signed=is_signed, is_long=is_long)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1674, in ParseInteger
>     result = _ParseAbstractInteger(text)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1704, in _ParseAbstractInteger
>     raise ValueError('Couldn\'t parse integer: %s' % orig_text)
> ValueError: Couldn't parse integer: '1'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\utils\label_map_util.py", line 171, in load_labelmap
>     text_format.Merge(label_map_string, label_map)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 719, in Merge
>     return MergeLines(
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 793, in MergeLines
>     return parser.MergeLines(lines, message)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 818, in MergeLines
>     self._ParseOrMerge(lines, message)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 837, in _ParseOrMerge
>     self._MergeField(tokenizer, message)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField
>     merger(tokenizer, message, field)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1042, in _MergeMessageField
>     self._MergeField(tokenizer, sub_message)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField
>     merger(tokenizer, message, field)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1076, in _MergeScalarField
>     value = _ConsumeInt32(tokenizer)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1573, in _ConsumeInt32
>     return _ConsumeInteger(tokenizer, is_signed=True, is_long=False)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\google\protobuf\text_format.py", line 1654, in _ConsumeInteger
>     raise tokenizer.ParseError(str(e))
> google.protobuf.text_format.ParseError: 3:6 : '	id: '1'
> ': Couldn't parse integer: '1'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "d:\Open-Source_Contribution\object_dectection_tf\Tensorflow\scripts\generate_tfrecord.py", line 61, in <module>
>     label_map = label_map_util.load_labelmap(args.labels_path)
>   File "D:\Open-Source_Contribution\object_dectection_tf\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\utils\label_map_util.py", line 173, in load_labelmap
>     label_map.ParseFromString(label_map_string)
> TypeError: a bytes-like object is required, not 'str'
> ```

i have same issue with you, how can u solved it?
